### PR TITLE
Fix bug about team selection by not reusing team selector GUI

### PR DESCRIPTION
**Pull request by boiscljo**
## Description

Fix the bug preventing people from choosing teams with the GUI if 2 people have the same GUI open by not reusing GUIs
**Tested minecraft versions:**
1.19.2
### Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Misat11** [comment]
Probably not the way I wanted to fix it, but if it works, why not ;)

**Comment by Misat11** [comment]
I hope it won't cause memory leak

**Comment by boiscljo** [comment]
> 
To prevent memory leak you could always add a .clear() to the list, but I don't think it's needed

**Comment by Misat11** [comment]
I mean if someone opens the gui, you are holding the instance in the memory, if someone opens the gui hundred times, there are hundred instances of this until the waiting ends

**Comment by boiscljo** [comment]
> I mean if someone opens the gui, you are holding the instance in the memory, if someone opens the gui hundred times, there are hundred instances of this until the waiting ends

there is just a limited about of time where the player can actually do it and a GUI is very low in memory. I'm more concerned about if the Game object ends with the game itself releasing the list. That might be a leak if it doesn't. I'm used to SBA Arenas which ends with the game.

**Comment by pronze** [comment]
There is a memory leak because you're not clearing the list lol. Also you guys are overthinking it xd

**Pull request merged**
